TMP

diff --git a/.github/workflows/check-cherry-pick.yml b/.github/workflows/check-cherry-pick.yml
--- a/.github/workflows/check-cherry-pick.yml
+++ b/.github/workflows/check-cherry-pick.yml
@@ -1,6 +1,6 @@
 name: "Check cherry-picks"
 on:
-  pull_request:
+  pull_request_target:
 
 env:
   PICKABLE_BRANCHES: master staging
@@ -8,11 +8,14 @@ env:
 jobs:
   check:
     runs-on: ubuntu-latest
+    #if: github.repository_owner == 'NixOS'
     steps:
     - uses: actions/checkout@v3
       with:
         fetch-depth: 0
     - run: |
+        problem=0
+
         git rev-list '${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}' \
           -E -i --grep="cherry.*[0-9a-f]{40}" \
           | while read commit_sha ; do
@@ -27,17 +30,21 @@ jobs:
             | egrep -oi -m1 '[0-9a-f]{40}'
           )
           if [ "$?" = "0" ] ; then
-            echo "⁉ Couldn't locate commit hash in message"
+            echo "  ⁉ Couldn't locate commit hash in message"
             continue
           fi
 
           for $picked_branch in $PICKABLE_BRANCHES ; do
             if git merge-base --is-ancestor "$original_commit_sha" "picked_branch" ; then
-              echo "✔ $original_commit_sha present in branch $picked_branch"
+              echo "  ✔ $original_commit_sha present in branch $picked_branch"
+
 
               continue 2
             fi
           done
 
-          echo "✘ $original_commit_sha not found in any pickable branch"
+          echo "  ✘ $original_commit_sha not found in any pickable branch"
+          problem=1
         done
+
+        exit $problem
